apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldeployment
  labels:
    team: development
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rolling
  #Strateji, imajları akıcı olarak güncellemek için kullanılır.
  # RollingUpdate: Ortamda enfazla +2 (maxSurge) pod olmasını sağlar ve en fazla -2 (maxUnavailable) pod a kadar işlemler durur.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80