apiVersion: v1
kind: Service
metadata:
  name: postgresqlpool
spec:
  clusterIP: None
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    team: development
spec:
  serviceName: postgresqlpool
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgressecret
        volumeMounts:
        - name: postgresqldataclaim
          mountPath: /var/lib/postgresql/data
          subPath: postgresql.data
  volumeClaimTemplates:
  - metadata:
      name: postgresqldataclaim
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi