apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ozgurozturknet/k8s:blue
        ports:
        - containerPort: 80
        
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        # Readiness probe lar yine liveness probelar gibi 3 çeşittir "httpGet", "exec", "tcpSocket".
        # Readiness probelar eğer container başlamaya hazırsa, yani container içerisindeki çalışan sistem bize yanıt vermek için hazırsa ki bazı sistemlerin başlangıcı zaman alabilir.
        # İşte o zaman ilgili POD un atanması gereken SERVICE e dahil edilip edilmeyeceğini belirler. 
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80