apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
  - name: www
    image: nginx:alpine
    ports:
      - name: www
        containerPort: 80
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /usr/share/nginx/html
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-claim