apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod1
spec:
  containers:
  - name: nodeaffinity1
    image: ozgurozturknet/k8s
  
  # Affinity ile "podun" hangi "node" üzerinde çalışması gerektiği söylenir.
  # Örneğin bir uygulamaya, hddtype=ssd labelina sahip bir node üzerinde çalışması gerektiği söylenebilir.
  # Bu label tanımı yoksa pod pending de kalır.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In #In, NotIn, Exists, DoesNotExist
            values:
            - blue
            
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod2
spec:
  containers:
  - name: nodeaffinity2
    image: ozgurozturknet/k8s
  
  #Yine aynı şekilde pod un, belirtilen labelın olduğu node üzerinde, deploy olması gerektiği söylenebilir.
  # Fakat burada "olsa iyi olur; ilk olarak bu şartlar varsa yapılsın,
  # yoksa başka bir node üzerinde de bu pod çalışabilir" çıkarımında bulunulabilir.
  # weight ise hangi şartın öncelikli olduğunu belirtir. Şartın sağlandığı ilk node a, pod deploy edilir.
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - blue
      - weight: 2
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - red
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod3
spec:
  containers:
  - name: nodeaffinity3
    image: ozgurozturknet/k8s
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: Exists #In, NotIn, Exists, DoesNotExist