# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postgresql.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10postgresql.proto\x12\x08producer\"*\n\x19\x65xecuteSelectQueryRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\"*\n\x19\x65xecuteInsertQueryRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\"S\n\x11\x63onnect2DBRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"#\n\x13\x64isconnectDBRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\",\n\x1a\x65xecuteSelectQueryResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\",\n\x1a\x65xecuteInsertQueryResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"$\n\x12\x63onnect2DBResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"&\n\x14\x64isconnectDBResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xee\x02\n\npostgresql\x12\x61\n\x12\x65xecuteSelectQuery\x12#.producer.executeSelectQueryRequest\x1a$.producer.executeSelectQueryResponse\"\x00\x12\x61\n\x12\x65xecuteInsertQuery\x12#.producer.executeInsertQueryRequest\x1a$.producer.executeInsertQueryResponse\"\x00\x12I\n\nconnect2DB\x12\x1b.producer.connect2DBRequest\x1a\x1c.producer.connect2DBResponse\"\x00\x12O\n\x0c\x64isconnectDB\x12\x1d.producer.disconnectDBRequest\x1a\x1e.producer.disconnectDBResponse\"\x00\x62\x06proto3')



_EXECUTESELECTQUERYREQUEST = DESCRIPTOR.message_types_by_name['executeSelectQueryRequest']
_EXECUTEINSERTQUERYREQUEST = DESCRIPTOR.message_types_by_name['executeInsertQueryRequest']
_CONNECT2DBREQUEST = DESCRIPTOR.message_types_by_name['connect2DBRequest']
_DISCONNECTDBREQUEST = DESCRIPTOR.message_types_by_name['disconnectDBRequest']
_EXECUTESELECTQUERYRESPONSE = DESCRIPTOR.message_types_by_name['executeSelectQueryResponse']
_EXECUTEINSERTQUERYRESPONSE = DESCRIPTOR.message_types_by_name['executeInsertQueryResponse']
_CONNECT2DBRESPONSE = DESCRIPTOR.message_types_by_name['connect2DBResponse']
_DISCONNECTDBRESPONSE = DESCRIPTOR.message_types_by_name['disconnectDBResponse']
executeSelectQueryRequest = _reflection.GeneratedProtocolMessageType('executeSelectQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTESELECTQUERYREQUEST,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.executeSelectQueryRequest)
  })
_sym_db.RegisterMessage(executeSelectQueryRequest)

executeInsertQueryRequest = _reflection.GeneratedProtocolMessageType('executeInsertQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEINSERTQUERYREQUEST,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.executeInsertQueryRequest)
  })
_sym_db.RegisterMessage(executeInsertQueryRequest)

connect2DBRequest = _reflection.GeneratedProtocolMessageType('connect2DBRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECT2DBREQUEST,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.connect2DBRequest)
  })
_sym_db.RegisterMessage(connect2DBRequest)

disconnectDBRequest = _reflection.GeneratedProtocolMessageType('disconnectDBRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTDBREQUEST,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.disconnectDBRequest)
  })
_sym_db.RegisterMessage(disconnectDBRequest)

executeSelectQueryResponse = _reflection.GeneratedProtocolMessageType('executeSelectQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTESELECTQUERYRESPONSE,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.executeSelectQueryResponse)
  })
_sym_db.RegisterMessage(executeSelectQueryResponse)

executeInsertQueryResponse = _reflection.GeneratedProtocolMessageType('executeInsertQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEINSERTQUERYRESPONSE,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.executeInsertQueryResponse)
  })
_sym_db.RegisterMessage(executeInsertQueryResponse)

connect2DBResponse = _reflection.GeneratedProtocolMessageType('connect2DBResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECT2DBRESPONSE,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.connect2DBResponse)
  })
_sym_db.RegisterMessage(connect2DBResponse)

disconnectDBResponse = _reflection.GeneratedProtocolMessageType('disconnectDBResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTDBRESPONSE,
  '__module__' : 'postgresql_pb2'
  # @@protoc_insertion_point(class_scope:producer.disconnectDBResponse)
  })
_sym_db.RegisterMessage(disconnectDBResponse)

_POSTGRESQL = DESCRIPTOR.services_by_name['postgresql']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTESELECTQUERYREQUEST._serialized_start=30
  _EXECUTESELECTQUERYREQUEST._serialized_end=72
  _EXECUTEINSERTQUERYREQUEST._serialized_start=74
  _EXECUTEINSERTQUERYREQUEST._serialized_end=116
  _CONNECT2DBREQUEST._serialized_start=118
  _CONNECT2DBREQUEST._serialized_end=201
  _DISCONNECTDBREQUEST._serialized_start=203
  _DISCONNECTDBREQUEST._serialized_end=238
  _EXECUTESELECTQUERYRESPONSE._serialized_start=240
  _EXECUTESELECTQUERYRESPONSE._serialized_end=284
  _EXECUTEINSERTQUERYRESPONSE._serialized_start=286
  _EXECUTEINSERTQUERYRESPONSE._serialized_end=330
  _CONNECT2DBRESPONSE._serialized_start=332
  _CONNECT2DBRESPONSE._serialized_end=368
  _DISCONNECTDBRESPONSE._serialized_start=370
  _DISCONNECTDBRESPONSE._serialized_end=408
  _POSTGRESQL._serialized_start=411
  _POSTGRESQL._serialized_end=777
# @@protoc_insertion_point(module_scope)
