apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  
  # Annotation -> Labellar harici bilgi vermek için kullanılır.
  # Bazı ingress-controller ların ayarlamaları içinde kullanılır.
  annotations:
    owner: "Blitz Krieg"
    notification-email: "admin@k8sfundamentals.com"
    releasedate: "07.05.2022"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    ports:
    - containerPort: 80