# Bir pod içerisinde sadece bir containerın çalıştırılması önerilir.
# Bazen network ve volume bazında haberleşmesi gereken iki uygulama olduğunda bu iki container aynı podda oluşturulabilir.
# Örnek olarak githubdan 15 sn ye bir ana kodu çeken bir "sidecarcontainer" ile webservisi olan nginx in aynı podda oluşturulması.
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: webcontainer
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: sharedvolume
      mountPath: /usr/share/nginx/html
    hostNetworking: true
  - name: sidecarcontainer
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -O /var/log/index.html https://raw.githubusercontent.com/ozgurozturknet/hello-world/master/index.html; sleep 15; done"]
    volumeMounts:
    - name: sharedvolume
      mountPath: /var/log
  volumes:
  - name: sharedvolume
    emptyDir: {}