version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tenis
      POSTGRES_PASSWORD: tenis
      POSTGRES_DB: tenis
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - tennis-net
    volumes:
      - tennis-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 4546:8080
    networks:
      - tennis-net
volumes:
  tennis-data:
networks:
  tennis-net:
    driver: bridge
