# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import AlgorithmService_pb2 as AlgorithmService__pb2


class AlgorithmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createBulkEntries = channel.stream_stream(
                '/SamplePackage.AlgorithmService/createBulkEntries',
                request_serializer=AlgorithmService__pb2.AlgorithmServiceRequest.SerializeToString,
                response_deserializer=AlgorithmService__pb2.AlgorithmServiceResponse.FromString,
                )


class AlgorithmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createBulkEntries(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createBulkEntries': grpc.stream_stream_rpc_method_handler(
                    servicer.createBulkEntries,
                    request_deserializer=AlgorithmService__pb2.AlgorithmServiceRequest.FromString,
                    response_serializer=AlgorithmService__pb2.AlgorithmServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SamplePackage.AlgorithmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlgorithmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createBulkEntries(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SamplePackage.AlgorithmService/createBulkEntries',
            AlgorithmService__pb2.AlgorithmServiceRequest.SerializeToString,
            AlgorithmService__pb2.AlgorithmServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
