# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x04main\"\x1e\n\x0eProcessRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1f\n\x0fProcessResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32@\n\x04Main\x12\x38\n\x07Process\x12\x14.main.ProcessRequest\x1a\x15.main.ProcessResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSREQUEST._serialized_start=20
  _PROCESSREQUEST._serialized_end=50
  _PROCESSRESPONSE._serialized_start=52
  _PROCESSRESPONSE._serialized_end=83
  _MAIN._serialized_start=85
  _MAIN._serialized_end=149
# @@protoc_insertion_point(module_scope)
