# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_main.ManagerService_pb2 as ManagerService__pb2


class ManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleProcess = channel.stream_stream(
                '/SamplePackage.ManagerService/SampleProcess',
                request_serializer=ManagerService__pb2.ManagerServiceRequest.SerializeToString,
                response_deserializer=ManagerService__pb2.ManagerServiceResponse.FromString,
                )


class ManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SampleProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.SampleProcess,
                    request_deserializer=ManagerService__pb2.ManagerServiceRequest.FromString,
                    response_serializer=ManagerService__pb2.ManagerServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SamplePackage.ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SampleProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/SamplePackage.ManagerService/SampleProcess',
            ManagerService__pb2.ManagerServiceRequest.SerializeToString,
            ManagerService__pb2.ManagerServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
