# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ManagerService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ManagerService.proto\x12\rSamplePackage\"%\n\x15ManagerServiceRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"&\n\x16ManagerServiceResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2t\n\x0eManagerService\x12\x62\n\rSampleProcess\x12$.SamplePackage.ManagerServiceRequest\x1a%.SamplePackage.ManagerServiceResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_MANAGERSERVICEREQUEST = DESCRIPTOR.message_types_by_name['ManagerServiceRequest']
_MANAGERSERVICERESPONSE = DESCRIPTOR.message_types_by_name['ManagerServiceResponse']
ManagerServiceRequest = _reflection.GeneratedProtocolMessageType('ManagerServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERSERVICEREQUEST,
  '__module__' : 'ManagerService_pb2'
  # @@protoc_insertion_point(class_scope:SamplePackage.ManagerServiceRequest)
  })
_sym_db.RegisterMessage(ManagerServiceRequest)

ManagerServiceResponse = _reflection.GeneratedProtocolMessageType('ManagerServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERSERVICERESPONSE,
  '__module__' : 'ManagerService_pb2'
  # @@protoc_insertion_point(class_scope:SamplePackage.ManagerServiceResponse)
  })
_sym_db.RegisterMessage(ManagerServiceResponse)

_MANAGERSERVICE = DESCRIPTOR.services_by_name['ManagerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANAGERSERVICEREQUEST._serialized_start=39
  _MANAGERSERVICEREQUEST._serialized_end=76
  _MANAGERSERVICERESPONSE._serialized_start=78
  _MANAGERSERVICERESPONSE._serialized_end=116
  _MANAGERSERVICE._serialized_start=118
  _MANAGERSERVICE._serialized_end=234
# @@protoc_insertion_point(module_scope)
