apiVersion: v1
kind: Service
metadata:
  name: brokerpool
spec:
  clusterIP: None
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: brokerdeployment
  labels:
    team: development
spec:
  serviceName: brokerpool
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.1.1
        ports:
          - containerPort: 9092
          - containerPort: 9101
        envFrom:
        - configMapRef:
            name: brokerenv
        volumeMounts:
        - name: brokerdataclaim
          mountPath: /var/lib/kafka/data
          subPath: broker.data
  volumeClaimTemplates:
  - metadata:
      name: brokerdataclaim
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 2Gi