apiVersion: v1
kind: Service
metadata:
  name: kafkaconnectpool
spec:
  clusterIP: None
  selector:
    app: kafkaconnect
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8083
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafkaconnectdeployment
  labels:
    team: development
spec:
  serviceName: kafkaconnectpool
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconnect
  template:
    metadata:
      labels:
        app: kafkaconnect
    spec:
      containers:
      - name: kafkaconnect
        image: confluentinc/cp-kafka-connect:7.1.1
        ports:
          - containerPort: 8083
        envFrom:
        - configMapRef:
            name: kafkaconnectenv
        volumeMounts:
        - name: kafkaconnectdataclaim
          mountPath: /data
          subPath: kafkaconnect.data
  volumeClaimTemplates:
  - metadata:
      name: kafkaconnectdataclaim
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 1Gi