apiVersion: v1
kind: Service
metadata:
  name: schemapool
spec:
  clusterIP: None
  selector:
    app: schemaregistry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schemaregistrydeployment
  labels:
    team: development
spec:
  serviceName: schemapool
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  template:
    metadata:
      labels:
        app: schemaregistry
    spec:
      containers:
      - name: schemaregistry
        image: confluentinc/cp-schema-registry:7.1.1
        ports:
          - containerPort: 8081
        envFrom:
        - configMapRef:
            name: schemaregistryenv
        volumeMounts:
        - name: schemadataclaim
          mountPath: /data
          subPath: schemaregistry.data
  volumeClaimTemplates:
  - metadata:
      name: schemadataclaim
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 1Gi
